name: Pamplejuce

on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release
  BUILD_DIR: Builds
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_MULTIARCH: 1

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-14
            pluginval-binary: pluginval.app/Contents/MacOS/pluginval
            extra-flags: -G Ninja -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          - name: Windows
            os: windows-latest
            pluginval-binary: ./pluginval.exe
            # Use the MSVC compiler exposed by msvc-dev-cmd instead of clang-cl + Ninja
            extra-flags: -G Ninja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_MSVC_WARNING_LEVEL=4

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja (Windows)
        if: (runner.os == 'Windows')
        run: choco install ninja

      - name: Install macOS Deps
        if: ${{ runner.os == 'macOS' }}
        run: brew install ninja osxutils

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Cache the build
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Configure
        run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache ${{ matrix.extra-flags }} .

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Test & Benchmarks
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest --verbose --output-on-failure

      - name: Set additional env vars for next steps
        run: |
          # Define HomeChords names
          PROJECT_NAME="HomeChords"
          PRODUCT_NAME="Home-Chords"
          VERSION=$(cat VERSION | tr -d '[:space:]')

          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PRODUCT_NAME=$PRODUCT_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          ARTIFACTS_PATH=${{ env.BUILD_DIR }}/${PROJECT_NAME}_artefacts/${{ env.BUILD_TYPE }}
          echo "ARTIFACTS_PATH=$ARTIFACTS_PATH" >> $GITHUB_ENV
          echo "VST3_PATH=$ARTIFACTS_PATH/VST3/${PRODUCT_NAME}.vst3" >> $GITHUB_ENV
          echo "AU_PATH=$ARTIFACTS_PATH/AU/${PRODUCT_NAME}.component" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${PRODUCT_NAME}-${VERSION}-${{ runner.os }}" >> $GITHUB_ENV

      - name: Pluginval
        run: |
          curl -LO "https://github.com/Tracktion/pluginval/releases/download/v1.0.4/pluginval_${{ runner.os }}.zip"
          7z x pluginval_${{ runner.os }}.zip
          ${{ matrix.pluginval-binary }} --strictness-level 10 --verbose --validate "${{ env.VST3_PATH }}"

      - name: Add Custom Icons (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          sips -i packaging/pamplejuce.icns
          DeRez -only icns packaging/pamplejuce.icns > /tmp/icons
          Rez -a /tmp/icons -o "${{ env.VST3_PATH }}/Icon"$'\r'
          Rez -a /tmp/icons -o "${{ env.AU_PATH }}/Icon"$'\r'
          SetFile -a C "${{ env.VST3_PATH }}"
          SetFile -a C "${{ env.AU_PATH }}"

      - name: Zip (macOS)
        if: ${{ runner.os == 'macOS' }}
        working-directory: ${{ env.ARTIFACTS_PATH }}
        run: 7z a -tzip "${{ env.ARTIFACT_NAME }}.zip" "-xr!lib${{ env.PRODUCT_NAME }}_SharedCode.a" .

      - name: Generate Installer
        if: ${{ runner.os == 'Windows' }}
        run: |
          iscc "packaging\installer.iss"
          mv "packaging/Output/${{ env.ARTIFACT_NAME }}.exe" "${{ env.ARTIFACTS_PATH }}/"

      - name: Upload Exe (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}.exe
          path: "${{ env.ARTIFACTS_PATH }}/${{ env.ARTIFACT_NAME }}.exe"

      - name: Upload Zip (macOS)
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}.zip
          path: "${{ env.ARTIFACTS_PATH }}/${{ env.ARTIFACT_NAME }}.zip"

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v8

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            */*.exe
            */*.zip
            */*.dmg